name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  schedule: # monthly
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate compose file
        run: docker compose -f docker-compose.yml config -q

      - name: Build images
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker compose -f docker-compose.yml \
            build --pull --progress=plain
